-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 09:01:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Financiera` DEFAULT CHARACTER SET utf8 ;
USE `Financiera` ;

-- -----------------------------------------------------
-- Table `Financiera`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Financiera`.`Estado` (
  `idEstado` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Financiera`.`Ingresos/Egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Financiera`.`Ingresos/Egresos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  `valor` INT NOT NULL,
  `estado_fk` INT NOT NULL,
  PRIMARY KEY (`id`),
	FOREIGN KEY (`estado_fk`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    on delete cascade on update cascade)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
